### ISSUE TITLE
GPU memory requirements for training

### ISSUE THREAD

**Issue by dongzhang04** [vitusbenson/greenearthnet#5]
Hi Vitus, 

I've been able to successfully run the training script for Contextformer 6M with two 40GB A100 GPUs on our HPC system for regions with little data (just a few hundred minicubes), however when it comes to larger datasets, such as 29SND with over 2000 minicubes, our GPUs run out of memory just by loading the first epoch:

<img width="931" height="841" alt="Image" src="https://github.com/user-attachments/assets/4701e286-fa58-4e1d-a1c3-111834a1c112" />

<img width="1424" height="75" alt="Image" src="https://github.com/user-attachments/assets/2a019632-2ec2-45a3-b652-3a76fa700646" />

<img width="1498" height="70" alt="Image" src="https://github.com/user-attachments/assets/c69e984f-0454-4762-bd09-2e6a4dd943ea" />

Of course, the screenshots show that there is little memory available for the training process (process 41259 should be a separate process to my understanding), however this HPC cluster is the only one with GPUs I currently have access to and is frequently in use so I cannot guarantee an amount of memory for the training jobs. 

Also, I'm not sure how helpful these are but the SLURM specifications I've set are as follows:
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-gpu=32
#SBATCH --mem-per-cpu=3G
#SBATCH --gpus-per-task=2

and the config I'm using is:

```yaml
Architecture: "contextformer"

Seed: 42

Setting: greenearthnet

Logger:
    save_dir: "experiments/"

Checkpointer:
    save_top_k: 1
    save_last: True
    every_n_epochs: 1

Trainer:
    accelerator: 'gpu'
    devices: 2
    strategy: 'ddp'
    log_every_n_steps: 32
    max_epochs: 100
    gradient_clip_val: 1

Data:
    test_track: "ood-t_chopped"
    train_batch_size: 16
    val_batch_size: 8
    test_batch_size: 8
    num_workers: 32
    dl_cloudmask: True
    allow_fastaccess: False
    new_valset: True

Task:
    loss:
        name: "MaskedL2NDVILoss"
        lc_min: 10
        lc_max: 40
        ndvi_pred_idx: 0
        ndvi_targ_idx: 0
        pred_mask_value: -1
        scale_by_std: False
    context_length: 10
    target_length: 20
    n_stochastic_preds: 1
    optimization:
        optimizer:
            - 
                name: AdamW
                args: 
                    betas: [0.9, 0.999]
                lr_per_sample: 0.00000125
        lr_shedule:
            -
                name: MultiStepLR
                args:
                    milestones: [190] #[2, 20, 50, 90]
                    gamma: 0.1
    n_log_batches: 2
    compute_metric_on_test: True

Model:
    patch_size: 4
    n_image: 8
    n_weather: 24
    n_hidden: 256
    n_out: 1
    n_heads: 8
    depth: 3
    mlp_ratio: 4.0
    mtm: True
    leave_n_first: 3
    p_mtm: 0.7
    p_use_mtm: 0.5
    mask_clouds: True
    predict_delta: False
    predict_delta0: False
    predict_delta_avg: False
    predict_delta_max: False
    add_last_ndvi: True
    add_mean_ndvi: False
    pvt: True
    pvt_frozen: False
```

We're just looking for any tricks you may know of that can help reduce the GPU memory requirements for training jobs, and as you may have seen Richard say in his email, it's not a big deal if there isn't anything to be done about it. 

Thanks!

**Comment by vitusbenson** [comment]
Hi @dongzhang04 - cool !
Two thoughts: 
1. If you run out of GPU memory (CUDA out of memory error - seems to be the case), then decrease the minibatch size (```train_batch_size: 16
    val_batch_size: 8
    test_batch_size: 8```) to smaller numbers. This should reduce GPU memory use.
2. If you run out of CPU memory (i.e. a regular OOM) -- then reduce the `num_workers` that the PyTorch dataloader is allowed to use.

**Comment by dongzhang04** [comment]
Thanks! 
I was able to confirm that halving the batch sizes works for us.
